force-app/main/default/objects/Consulta__c/Consulta__c.object-meta.xml
<CustomObject>
    <label>Consulta</label>
    <nameField>
        <label>Nome de Consulta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Consulta__c/fields/Data_da_Consulta__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Consulta__c</fullName>
    <label>Data da Consulta</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Consulta__c/fields/Dentista__c.field-meta.xml
<CustomField>
    <fullName>Dentista__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dentista</label>
    <referenceTo>Dentista__c</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Consultas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consulta__c/fields/Hora_da_Consulta__c.field-meta.xml
<CustomField>
    <fullName>Hora_da_Consulta__c</fullName>
    <label>Hora da Consulta</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Dentista__c/Dentista__c.object-meta.xml
<CustomObject>
    <label>Dentista</label>
    <nameField>
        <label>Nome de Dentista</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dentistas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Consulta.cls
public class Consulta {

    public static Boolean existeConflito(
        Id dentistaId,
        Date dataConsulta,
        Time horaConsulta,
        Id consultaAtualId
    ) {

        if (dentistaId == null || dataConsulta == null || horaConsulta == null) {
            return false;
        }

        List<Consulta__c> consultas = [
            SELECT Id
            FROM Consulta__c
            WHERE Dentista__c = :dentistaId
            AND Data_da_Consulta__c = :dataConsulta
            AND Hora_da_Consulta__c = :horaConsulta
            AND Id != :consultaAtualId
            LIMIT 1
        ];

        return !consultas.isEmpty();
    }
}